features:
  groups:
    enabled: true

forms_api:
  # URL to form-api endpoints
  base_url: http://localhost:9292
  # Authentication key to authenticate forms-runner to forms-api
  auth_key: changeme

# Use mock authentication
# in development use 'mock_gds_sso' to always be logged in or 'developer' to use a
# mock flow through omniauth
auth_provider: mock_gds_sso
