# Used to add feature flags in the app to control access to certain features.
features: []

forms_api:
  # URL to form-api endpoints
  base_url: http://localhost:9292
  # Authentication key to authenticate forms-runner to forms-api
  auth_key: changeme

# Use mock authentication
auth_provider: mock_gds_sso
