features:
  groups:
    enabled: false
    organisations:
      government_digital_service: true

# Use real authentication
auth_provider: gds_sso

mailchimp:
  api_prefix: "us12"
  active_users_list: c9cc8511c6
  mou_signers_list: ef5e72c003
