forms_api:
  # URL to form-api endpoints
  base_url: http://localhost:9292
  # Authentication key to authenticate forms-runner to forms-api
  auth_key:


# When set to true, All pages will render 'Maintenance mode'
maintenance_mode_enabled: false

forms_runner:
  # Base URL to point users to the app in the UI
  url: runner-host

# No default strategy as Warden test mode is used
auth_provider: ""