name: Deploy to GOV.UK PaaS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref_to_deploy }}

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@bc1dd263b68cb5626dbb55d5c89777d79372c484 # v1.117.0
        with:
          bundler-cache: true

      - name: Precompile assets
        run: bundle exec rake assets:precompile

      - name: Install cloudfoundry
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: Deploy to Gov.uk PaaS
        id: deploy-to-paas
        shell: bash
        run: |
          cf api ${{ secrets.CF_API }}
          cf auth "${{ secrets.CF_USER }}" "${{ secrets.CF_PASSWORD }}"
          cf target -o ${{ secrets.CF_ORGANISATION }} -s ${{ secrets.CF_SPACE }}
          cf push --strategy rolling \
            --var PAAS_ENVIRONMENT=dev \
            --var SETTINGS__SERVICE_UNAVAILABLE=false \
            --var GDS_SSO_OAUTH_ID=${{ secrets.GDS_SSO_OAUTH_ID }} \
            --var GDS_SSO_OAUTH_SECRET=${{ secrets.GDS_SSO_OAUTH_SECRET }} \
            --var SETTINGS__GOVUK_NOTIFY__API_KEY=${{ secrets.SETTINGS__GOVUK_NOTIFY__API_KEY }} \
            --var SETTINGS__FORMS_RUNNER__URL=${{ secrets.RUNNER_BASE }} \
            --var GOVUK_APP_DOMAIN=${{ secrets.GOVUK_APP_DOMAIN }} \
            --var SETTINGS__SENTRY__DSN=${{ secrets.SENTRY_DSN }} \
            --var SETTINGS__SENTRY__ENVIRONMENT=dev \
            --var SETTINGS__FORMS_API__BASE_URL=${{ secrets.API_BASE }} \
            --var INSTANCES=2 \
            --var SETTINGS__FORMS_API__AUTH_KEY=${{ secrets.API_KEY }} \
            --var SETTINGS__FEATURES__BASIC_ROUTING=true
