name: Trello Poster
on:
  pull_request:
    types: [opened, edited]
jobs:
  trello-poster:
    uses: alphagov/forms-deploy/.github/workflows/trello-poster.yml@main
    secrets:
      TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
      TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
